spring:
  application:
    name: person-service
  datasource:
    url: jdbc:mysql://localhost:3306/eureka-shop
    username: admin
    password: admin
    hikari:
      allow-pool-suspension: true
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8082
  servlet:
    context-path: /api/v1/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka