spring:
  application:
    name: person-service
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database: eureka
      auto-index-creation: true

server:
  port: 8082
  servlet:
    context-path: /api/v1/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka